name: sandbox
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  auto_route: ^4.0.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.0.3
  hooks_riverpod: ^2.0.0-dev.9
  visibility_detector: ^0.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  auto_route_generator: ^4.0.0

  flutter_lints: ^2.0.0
  freezed: ^2.0.3+1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
